name: Deploy FastAPI Backend to Azure

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/deploy.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy backend to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: tech0-gen-11-step3-2-py-62
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_PY_62 }}
          package: ./backend
